version: "3.8"

services:

  # Our Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./linkedin  
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./Linkedinbackend
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=postgres  # Use the service name as the host
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Admin
      - DATABASE_NAME=linkedin
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=linkedin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: